import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Questrial } from 'next/font/google'

import "@fonts/css/switzer.css";
import "../globals.css";

import "@fonts/font-awesome.min.css";

import "@css/plugins/bootstrap-grid.css";

import "@css/plugins/swiper.min.css";

import "@css/plugins/magnific-popup.css";

import Preloader from "@/layouts/Preloader";
import "@css/style.css";

const secondary_font = Questrial({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-secondary',
  display: 'swap',
  adjustFontFallback: false,
})

export const metadata = {
  title: "Plax - Finance & Fintech React NextJS Template",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  // Await params before using
  const { locale } = await params;

  // Providing all messages to the client side
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${secondary_font.variable}`}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Preloader />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

